image: registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY

stages:
  - push_config

Connect to Cisco Sandbox and push new config:
  stage: push_config
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /Ansible Managed Backup .*/
      when: never
    - changes:
      - .gitlab-ci.yml
      - push_configs.yml
      - ansible_managed_inventory
      when: never
    - when: always

  script:
    - CHANGES="$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)"
    - echo $CHANGES
    - CHANGED_HOST="$(basename $CHANGES)"
    - echo $CHANGED_HOST
    - echo "[defaults]\nhost_key_checking = False" > /etc/ansible/test.cfg
    - ansible-playbook push_configs.yml -i ansible_managed_inventory -e "ANSIBLE_CONFIG=/etc/ansible/test.cfg CHANGES=${CHANGES} CHANGED_HOST=${CHANGED_HOST} CSR1000V_HOST=${CSR1000V_HOST} CSR1000V_USER=${CSR1000V_USER} CSR1000V_PASS=${CSR1000V_PASS} CSR1000V_SSH=${CSR1000V_SSH}" -vvv


