image: ansible:latest

stages:
  - push_config

Connect to Cisco Sandbox and push new config:
  stage: push_config
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Ansible Managed Backup .*/
  script:
    - echo "this is not a backup"
