image: registry.gitlab.com/$DOCKER_USERNAME/$DOCKER_REPOSITORY

stages:
  - push_config

Connect to Cisco Sandbox and push new config:
  stage: push_config
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /Ansible Managed Backup .*/
      when: never
    - when: always
    - changes:
      - .gitlab-ci.yml
      when: never
    - when: always

  script:
    - files=(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
    - echo $files

