image: ansible:latest

stages:
  - push_config

Connect to Cisco Sandbox and push new config:
  stage: push_config
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /Ansible Managed Backup .*/
      when: never
    - when: always
  script:
    - echo "this is not a backup"

